### PR TITLE
march should be set to native instead of core2

### PR DESCRIPTION
**Pull request by hnhx**

### CODE REVIEW

**Comment by danielkrupinski** [comment]
It's to support CPUs older than the one used to build the project.

**Comment by hnhx** [comment]
Why is that good? In case of this project people build the binary for themself, not for others, therefore I don't see the reason for this to be core2. I have a Ryzen CPU for an example, so core2 is not good for me at all.

**Comment by danielkrupinski** [comment]
Do you have performance measurements with `-march=native` in your case?

**Comment by hnhx** [comment]
I haven't done measurements however `-march=native` would be a better default option since gcc (or any other compiler) will get the best out of the CPU. If you don't want `-march=native` then I would just recommend removing the march flag entirely, that would be still better than just defaulting to core2 for every user.

**Comment by hnhx** [comment]
As I said I think it should be a priority that the user gets a more optimized binary for themself, instead of getting a less optimized one that they can share with others. I doubt people build binaries of this project just to share it with others.

**Comment by danielkrupinski** [comment]
I'm not convinced that the default should be changed. Maybe it would be better to add a CMake option which would set `-march=native`?

**Pull request closed without merging**
